- job:
    name: deploy-zuul
    description: "Deploy Gerrit's Zuul"
    secrets:
      - secret: deploy-zuul-credentials
        name: zuul_deploy
    run:
      - playbooks/deploy.yaml
      - playbooks/checkers.yaml
    # Run on the executor only (an empty nodeset)
    nodeset:
      nodes: []

- secret:
    name: deploy-zuul-credentials
    data:
      server: "https://10.0.0.1:443"
      cert: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lRWW9OSEJiWlBvUXpEZ2JCMVNhOGFLekFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlSbE5ETXhZVFU1WWkwNFptRTFMVFJsT1dRdFlqRTFZeTA1WmpNeE16UmpNR1psTUdFdwpIaGNOTVRreE1qSXdNVFl5TnpNMldoY05NalF4TWpFNE1UY3lOek0yV2pBdk1TMHdLd1lEVlFRREV5UmxORE14CllUVTVZaTA0Wm1FMUxUUmxPV1F0WWpFMVl5MDVaak14TXpSak1HWmxNR0V3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNoS2k4cTJ5d2N4WWR4OHlQQmZzMXlGUmJuZ1ZXK29GUzFYV1FlKy9pTgo4a2M4K05IU3I2RGNFQUtGVExnMTU3VTNiOE5TdG9MdEdUNUtoV010MHh2NEcrQVc5Qy9GNzFzWWhscThGdXkxCkphQWZOeCtydlZEeW80YnJ2bU1ubXAwWmpMZzNIUjVBMThXT2xBZW52OGtyRVZ2VnNYL1hZbnMzb2FWeUhGYVEKNzdDcUNlYWpqeS9uLzdSUlBKNDhReVVvVTNRZDRmV0xXQ0c5emxhNzZ4eHlFSVh0MWlMVGZ5NElGYk9pbFlYcwpUVzMvZ1ZObTRjZHZaQmtjeDlPWkNNZXN5aHBEK1ZTUkpuVkdUdHA5UmZVNWlHc3JiejdTVzh6S3ovVjI4amV4CjEzY2V0cWw4Mk5PUGs4cTRleDJsZmJibGdqUTJBSWIrZWNtYUJHaWQxWmtMQWdNQkFBR2pJekFoTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBawpuMEdRRGFYYW1Da2twY0ZneUI1bWlHd0s2NktLNnRqNG1Jc1ZDMG9DdWJ2bFQ0UDBFS2pJeDlad0hHeDJTK3ZiCnM1M2s4bmx5cHBtb1VYRXVxcUVLREpONlNMS3JhTFhWVGo4c1EwaExxbWltYTc4UmhTSVJMU3EraWJTMVlMSVcKakRvR3lzYXgzVE1mamEyRlU1ZC9IZXJHNHI5cWQxaXFMTnRiWU4xYWovUmJ3SUFvOFdqWE42WldkRDJic0hNaQpFVDFwbEQrSzhEb3E2R3MzbEt6c1k1Q1MyS1ZlSmVnWFhVc0dFMExIYjYwY3FvVldVMUhHc1NYTXJuTldrZVM0Cldrc0hSa0dpQVZBU21DMDZaZUM1d0lvSGNIYzJRTjhZTjdKTE9CV0FRUHhBRHlLc053OC9Eci8xS1VLdkZvZHkKSlhCNlhBS2pnUnFCdW9ROUJlMzkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      token: !encrypted/pkcs1-oaep
        - IDYYtDEJ/KSlML8e2ZUGqOSrO6juCIMdLfNJ2BmQOeM7Yma1ChN2X/sKVlY1Q96eGr1Zp
          fvDXj40bcloRtxTpWH5Hq6aaE3IDsOCCu8UxLZcjxiN5hd+me4iDhHXOjN8S4vpy69pT+
          enz2OgQo5YEzuAXmFIDMoYMyYiOtjgXYVc/jmu+FELCH7Fbjlc7gW9DXRospqIzF5YLjd
          VJxrtiKtQvaD5S/cu0qut2JpXGwt4pZRL0WXlHhZpLJwZC1ObrRSANjA/G8/uQ68ciRqg
          cr04DUNXLstiGp9EbnfFSYBaH9THXfipBLrd5W56UwCHBi0uhTLZC1oYPo0j6myZp1ZZk
          NNuCV/bMYe/3hYezKoq+SU9shtEXpw6pmePM9gwbsylNPVwobPOgNQHfKPA3VmG24RRF6
          V3O47OLcTvSKZOvASg3qpjRsOT+3fIYvXfCD/2kFTwgcJytBp9K8XS4UeZqvU50mslqm/
          DhX79C+EOktRj8ghHAyfFEKkm7jS7nPlOUoyqKIXWrS5CmGo61uuBXTfKi8z8a3zgyDwU
          77r95rp7mUh7FHr7IPTaVBrAM30TZfAeCb6kDjCb+e8LnL6pgqSdTp7k/Jz36nHjFWG33
          2wFLvcY1kr+pAfSoGfvLokg+h8wnQSrE11UmgWJNSrWBbChY4f2zvip4oJegVQ=
        - W5dQHaerYTzYOAnj/c8GrPHYr7ektCNiZJRpxWSGLPlTPKbacbPadOd3q+kncFZjFQEma
          6/jytNiwcaKEf+GTdp0DT4s1wGL1LDVVm+5sc69Fby7d0uigD6e2MErQPi0FY+IDk8I1w
          NWP0DkU7hgl+PUB79BeFvWlfvqsPeb1qeAoqoexfCJcncixxyeIlv0mifuuC6so6JTU4o
          rpiI9MuLUZXFSj/kacGZoAWDhOTssGrOK4+fuOZMARCvOJ0wDg8Mlu6RT78OcSBuc3UsD
          Bd4rsuQ2hXuIypeVq8qlmIIFAjM6O6jNxkKf2nlwG+nZTFN7eUwpNcxupO6te9HK9ZGaN
          gBfneQ8LddJWnw/nAi1Xefvp3DNq1q/MPUGeEUwTzvR442YIdxH0uBLUDrkLs2w8loZMc
          G7T8vNJ4KLC3wAf51gmxKE9n8WvpFYfMW6uFK62wBF4k4kJH5H7seEv+lOQI9cBm9IwWY
          VgbrAzuCFzcXTLwyGwNXYsWRbgb2FjAQx4iJKAD89uSlWadiB+AF3fOZFzwOrg2DEDjX5
          iDJ2PD53IehqfmnZptYQwwGm1Rxz05LxM2bKicFznJy0QXIFc+S3paqBBYRcd5434pQmh
          DUPD3ulIHUKNdXwBgXZHfaf/JxPDF0KiXOlyNs8pkBz1oZAEyQTowRKKT2XC9M=
      db_password: !encrypted/pkcs1-oaep
        - EhY0ajVtaLdoicAm35bdhZcrDRsz1YVAvA4rWyLUU3H8PQpNO78KNwROzGTQCQ1se2r+X
          QvqZVURNfHJAYasaB3qQ1GIVdj8kmOYKBFQbPO0slY+zQx57jvQvd8yL0W8gDohSbCX5N
          npyM+siH5U0cQCtlyDyCg2WJQ3WErau9oJ2cBGOpvYe/QJNDalFWVSPckQxlKp/H05yzs
          Xs6M36NbURAIAtiOGc3X5K9TTerdyMLJOqCa+oalLDKDHfRB76yJfyRKNbWF3aVxoSFXQ
          uKYsR8JvCzp+lRdjVv6HO+L9GU0gOPjXIEaZbXshovzLz0pK51u1SG97OyLM1QdrBKo4e
          tWuuoz9rgrs/Qu896tOmP4tjdeP81SYTcAOFIQeYXQdP+CgC1pL2pS0HWXycEan+WTcj/
          iRnR3UQ+r4FKzwBjA2Hygf8CFZEOBTVNvb8SIUIQd4FcGLSK1DArWDlx9Vk3aC87ZyV/g
          lEW4RYyH0lVgX+/1IWTzg9NxrjMk3zp8QxdwedBJj0v7gK0xFU63QC/en/CdQr77CqOOa
          TKG0IsEqjoHcXTjIsSybKsDoK9xpHko3uvNqlDWtixDeTg7Ku/EQMt7ceeYHhob6ICbjj
          E/5usYA/9npt9dPBnM2PKyR9b8ZZop6CYJSZplduvnPk2mYVbdtPdgHzTPCnPA=
      nodepool_private_key: !encrypted/pkcs1-oaep
        - mGUMLYmV/GeWKzDjH9vh0olnVDHJYzeXjZJegdCACyCCk2ziyRGRhrKYIAmLpESgYvEnF
          21HAx3Zb5/C8rYrhLBkgJGxQifmI61c8hbh9/qS1Sdl3lukTNAC95MbNQKyz5hkDMSYzz
          5Ta30mbXuBB6a+pDgU6+WV1XR0Bubf5IPW5AYxFLyE8EmVE8PQDdvlgD5vQuq7YAqy0Am
          eygUBMq9XGXi2vGCB5keOMm0BCeDEjIYU4yEpMEUfIhji8EjCP5Nc38riXCXbVOi3QFaN
          kFciE/D6ZqrM2Q9FUfqhNhsMSxxGVDGMGDdBh/6h1SOLrfU+0uQnsIlpcyxNqs7RbSZ8x
          7DaZp2B4WwR+y8I6sX+QTv3c69isl6R3Matp2kfRDQdlCdqd1YtpDs7q0zn9w2rr7J6lC
          CHCK6UoJIzmVx8F7i2HT8LhLxnyliUinUc0rox90YMIhYU74tNi7yfbOQusJq2/sWjOdo
          J8KCmAHxCasnyMIvua29DcVVOd7sRy8BBK4YqekwFlcP+iUzmMKto0Ot2RAv+TFppaWTK
          DkpXx/HkzSJ50ULloXxaYbLEh4+gIi/EWiBgjbqjRjqbRG7UVESbV3BoDl/9M/PvaYK58
          6+nt0j3jB4Zwb5JOBfIwjH+hxaM6mYT/Q3zrH1JcOWRUjVwE7fkAuP9Onz0wrI=
        - brm/rVpLUAhdmKhM/o/efzRht0DtadlEXJBBKv0/+TCqxLGci+ezMe8a4BnR7utAapknr
          gWSfhwpUe2d9yLRJliWmeuwIQ5tzPsw1xqOKyUHvPwIXZr+PI6y2hkwoVABdjgjHNOCe1
          qn0vZ98uijkVy9NAcsXj5HonYng2XmO8l5ecY/6ADO1xOG3edimFtr9LGft0QwXF9viu+
          TQUXej4L1fC2zu5ZcSafTlrdDB3lsE6fv4PIv6W3TbPb6D8P+3BOV/gIux0UqQ6bjEDEL
          xGoWJp/eqU6r8U4Db28AalJ4nbkdXNJyjuPxAeH17p0knCF8OAcCJXVGXnIuV+Q8AUhIX
          VYH24XSG/h2QKnWQlZo1Vohq/+1bwXYgxskHh6pod9C/mvhWWSqkde3HIX4GjTVHxcgAB
          q3Uf8ZsuXuAYHkNvxSCgX8wUzDliLLFYuCLhDGB4xWzyL7b1FxcO8QebkZ574AVSD2ZsT
          7S9Ju6nzXBbDLtpmEP+k7f1OwcfDMEU8ow0PggGkwMw/IM2Gf1Liu9WEEPj8wPpf5KPgg
          atOG7BIGL7Be0tGNtEVPz2QXCAlLJVzsZ+PS2Ko233iN32ukzbX+4oPNA7qghN5otaQHe
          KQIEA7U7LdcGJDXGAu5Rs/XB8nJEyN6mlRrmMjqxlucWtr0+kLphmHGPPmEbnQ=
        - dqcp5mwGuhjLV+2VkaBy9C00L7T0duMYgxAEXDRA8W/KYRJdJBcl1aXwLDrnwPyS1fvFt
          KTov+9cBOacuLDrLDd2PsXX8LafRXyzXGVHH68AOlBD0hJygVehtjemeKjms3jEyRIyM6
          Ao0QJvaTbBFIuaBEgsihyLzHZKGLc1Rue2+lYAE8lRzOHbQN5m3clacXdyXiwDhMXr8di
          XDGgrdDGuNjel/cDl4PyfxoF1Bec2s7ZBVHhc5XrZRDdir352Kj1FCRhjEtw+FSPB1931
          pl5umgIqntGz/QpNERKJGyiQZvTEA7xxcaRh11Lr4oJByS//DQhE6sLR5XKxkNRNMks3I
          XNZmPlT/cpjGnlNeqjvcsa2Kd04pDql/mAW7CRjaQqhOHoIobMgN5/k+PBfV8wq5HDy5p
          zNkxZH4CyPe3+/w9tYDkUJVDdzi9FvZzyQ9Yz7FLm4Rzo0FPR8F12tD3MjLWpbTBPSTVa
          7JO9DauwAGqgUrzMJDOvHeeCiAgZVJi6+WfbMfKJq2YwF0sGBvT8AUo6C+zjk2zM14gMX
          9gYmLl8bvhG5NG/0UmkRihI23rabaXecAi8gpEfHGFxyT2A7p5aU4uAZrEw+j8wJGv+Mp
          3Cuh5FqBEDcOZEyV98PkcLG4fw1Bxw4CwMquIV/8i94aq9iAai91GFphiauE1M=
        - aJGJRX4kVW7Omy0RmP9tRcwyxhNtQxjXksDuScoxSoWCkgTwCKHy1uMUgHTbQdY6AFU6h
          /TyHagEZBJQsbSS8dyuu6IIxt/sW0rStlvZUim9QUh6myqfDZ2gXWSHg/15wqp88H459d
          aZSyW/34MsSR14NzreBqrtlisWCTvaYDv26uixBRpj/mR4skKhu6aTnpG2S1j1N550hoJ
          NyASuXDeUVeyx/pfDT0eOcoKaytoYSyTFvZEn5CDvRiraadwgGFmDPL8SDasRsUz+XUMG
          IC6uaP3eVUz+GJj3KY0mVC+4Y5/fOgnYv73TOrCnRmHwl++ZPf7E36iZ1I0j9fpVOOX7R
          SqNMbiUbxZYfADMIfl9dy0EKFejL3h4QdZzUH0aMLUBcBjfvAz7a30uj27V79GfE678L7
          ucA+dFVZeWx1rbBSkg4whBQx3rMQmhiOd/QVnQP4Ib4ehldfoIUSVCiWjCUM/SQAF4CRl
          +QOUeG3c4zQXMKEVuc5gw4Yd+AkXg4XVwUCQVDLHiwyfIHQ0hA9CXfEo+TEbzqnX9WFwR
          KyJhi+QHpVH4PqgSiHq8qZeIc1svvAlAJMeGtB/okIc25lFnlHl5w2A9YewrRXB/gWM+7
          l+iQHZGof2amEuCkQGcrDiIfspzzW3Dugs88D4mmp6D0uFY2DgQaH206oxBuoE=

- project:
    check:
      jobs:
        - noop
    post:
      jobs:
        - deploy-zuul
