apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodepool
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jeblair/zuul-helm
    path: charts/nodepool
    helm:
      values: |
        clouds: ''
        builder:
          enabled: false
        config:
          secret: nodepool-config
  destination:
    namespace: zuul
    server: https://kubernetes.default.svc
