apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zuul
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jeblair/zuul-helm
    path: charts/zuul
    helm:
      values: |
        zookeeper:
          hosts: zookeeper.zookeeper
        executor:
          replicas: 1
        merger:
          replicas: 1
        web:
          replicas: 1
          host: gerrit-zuul.inaugust.com
          serviceType: NodePort
        scheduler:
          tenantConfigPath: /etc/zuul/tenant/main.yaml
          tenantConfigSecret: zuul-tenant-config
        connections:
          opendev:
            name: opendev
            driver: git
            baseurl: https://opendev.org
  destination:
    namespace: zuul
    server: https://kubernetes.default.svc
