---
apiVersion: v1
kind: Secret
metadata:
  namespace: zuul
  name: zuul-config
  labels:    
    app.kubernetes.io/name: zuul
    app.kubernetes.io/instance: zuul
    app.kubernetes.io/part-of: zuul
stringData:
  zuul.conf: |
    [gearman]
    server=zuul-gearman
    port=4730
    
    [zookeeper]
    hosts=zookeeper.zookeeper
    
    [gearman_server]
    start=true
    port=4730
    
    [web]
    listen_address=0.0.0.0
    root=https://gerrit-zuul.inaugust.com
    port=9000
    
    [scheduler]
    tenant_config=/etc/zuul/tenant/main.yaml
    
    [connection "opendev"]
    name=opendev
    driver=git
    baseurl=https://opendev.org
    
    [connection "gerrit"]
    name=gerrit
    driver=gerrit
    server=gerrit-review.googlesource.com
    canonical_hostname=gerrit.googlesource.com
    user=zuul
    stream_events=false
    auth_type=gcloud_service
---
apiVersion: v1
kind: Secret
metadata:
  namespace: zuul
  name: zuul-tenant-config
  labels:    
    app.kubernetes.io/name: zuul
    app.kubernetes.io/instance: zuul
    app.kubernetes.io/part-of: zuul
stringData:
  main.yaml: |
    - tenant:
        name: gerrit
        report-build-page: true
        web-root: http://localhost:3000/
        source:
          opendev:
            untrusted-projects:
              - zuul/zuul-jobs
          gerrit:
            config-projects:
              - zuul/config
            untrusted-projects:
              - zuul/ops 
---
apiVersion: v1
kind: Service
metadata:
  namespace: zuul
  name: zuul-executor
  labels:    
    app.kubernetes.io/name: zuul
    app.kubernetes.io/instance: zuul
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zuul-executor
spec:
  type: ClusterIP
  ports:
  - name: logs
    port: 7900
    protocol: TCP
    targetPort: logs
  selector:    
    app.kubernetes.io/name: zuul
    app.kubernetes.io/instance: zuul
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zuul-executor
---
apiVersion: v1
kind: Service
metadata:
  namespace: zuul
  name: zuul-gearman
  labels:    
    app.kubernetes.io/name: zuul
    app.kubernetes.io/instance: zuul
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zuul-scheduler
spec:
  type: ClusterIP
  ports:
  - name: gearman
    port: 4730
    protocol: TCP
    targetPort: gearman
  selector:    
    app.kubernetes.io/name: zuul
    app.kubernetes.io/instance: zuul
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zuul-scheduler
---
apiVersion: v1
kind: Service
metadata:
  namespace: zuul
  name: zuul-web
  labels:    
    app.kubernetes.io/name: zuul
    app.kubernetes.io/instance: zuul
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zuul-web
spec:
  type: NodePort
  ports:
  - name: zuul-web
    port: 9000
    protocol: TCP
    targetPort: zuul-web
  selector:    
    app.kubernetes.io/name: zuul
    app.kubernetes.io/instance: zuul
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zuul-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zuul
  name: zuul-merger
  labels:    
    app.kubernetes.io/name: zuul
    app.kubernetes.io/instance: zuul
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zuul-merger
spec:
  replicas: 0
  selector:
    matchLabels:      
      app.kubernetes.io/name: zuul
      app.kubernetes.io/instance: zuul
      app.kubernetes.io/part-of: zuul
      app.kubernetes.io/component: zuul-merger
  template:
    metadata:
      labels:        
        app.kubernetes.io/name: zuul
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/part-of: zuul
        app.kubernetes.io/component: zuul-merger
    spec:
      containers:
      - name: merger
        image: zuul/zuul-merger:latest
        args:
        - /usr/local/bin/zuul-merger
        - -d
        volumeMounts:
        - name: zuul-config
          mountPath: /etc/zuul
      volumes:
      - name: zuul-config
        secret:
          secretName: zuul-config
          defaultMode: 256
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zuul
  name: zuul-web
  labels:    
    app.kubernetes.io/name: zuul
    app.kubernetes.io/instance: zuul
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zuul-web
spec:
  replicas: 1
  selector:
    matchLabels:      
      app.kubernetes.io/name: zuul
      app.kubernetes.io/instance: zuul
      app.kubernetes.io/part-of: zuul
      app.kubernetes.io/component: zuul-web
  template:
    metadata:
      labels:        
        app.kubernetes.io/name: zuul
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/part-of: zuul
        app.kubernetes.io/component: zuul-web
    spec:
      containers:
      - name: web
        image: zuul/zuul-web:latest
        args:
        - /usr/local/bin/zuul-web
        - -d
        ports:
        - name: zuul-web
          containerPort: 9000
        volumeMounts:
        - name: zuul-config
          mountPath: /etc/zuul
      volumes:
      - name: zuul-config
        secret:
          secretName: zuul-config
          defaultMode: 256
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: zuul
  name: zuul-executor
  labels:    
    app.kubernetes.io/name: zuul
    app.kubernetes.io/instance: zuul
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zuul-executor
spec:
  serviceName: zuul-executor
  replicas: 1
  selector:
    matchLabels:      
      app.kubernetes.io/name: zuul
      app.kubernetes.io/instance: zuul
      app.kubernetes.io/part-of: zuul
      app.kubernetes.io/component: zuul-executor
  template:
    metadata:
      labels:        
        app.kubernetes.io/name: zuul
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/part-of: zuul
        app.kubernetes.io/component: zuul-executor
    spec:
      containers:
      - name: executor
        image: jeblair/zuul-executor:latest
        args:
        - /usr/local/bin/zuul-executor
        - -d
        ports:
        - name: logs
          containerPort: 7900
        volumeMounts:
        - name: zuul-config
          mountPath: /etc/zuul
        - name: authdaemon
          mountPath: /authdaemon
        securityContext:
          privileged: true
      volumes:
      - name: zuul-config
        secret:
          secretName: zuul-config
          defaultMode: 256
      - name: authdaemon
        hostPath:
          path: /var/authdaemon/executor
          type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: zuul
  name: zuul-scheduler
  labels:    
    app.kubernetes.io/name: zuul
    app.kubernetes.io/instance: zuul
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zuul-scheduler
spec:
  replicas: 1
  serviceName: zuul-scheduler
  selector:
    matchLabels:      
      app.kubernetes.io/name: zuul
      app.kubernetes.io/instance: zuul
      app.kubernetes.io/part-of: zuul
      app.kubernetes.io/component: zuul-scheduler
  template:
    metadata:
      labels:        
        app.kubernetes.io/name: zuul
        app.kubernetes.io/instance: zuul
        app.kubernetes.io/part-of: zuul
        app.kubernetes.io/component: zuul-scheduler
    spec:
      containers:
      - name: scheduler
        image: jeblair/zuul-scheduler:latest
        args:
        - /usr/local/bin/zuul-scheduler
        - -d
        ports:
        - name: gearman
          containerPort: 4730
        volumeMounts:
        - name: zuul-config
          mountPath: /etc/zuul
        - name: zuul-tenant-config
          mountPath: /etc/zuul/tenant
        - name: zuul-scheduler
          mountPath: /var/lib/zuul
      volumes:
      - name: zuul-config
        secret:
          secretName: zuul-config
          defaultMode: 256
      - name: zuul-tenant-config
        secret:
          secretName: zuul-tenant-config
          defaultMode: 256
      serviceAccountName: zuul
  volumeClaimTemplates:
  - metadata:
      name: zuul-scheduler
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 80Gi
