---
apiVersion: v1
kind: Namespace
metadata:
  name: zookeeper
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: zookeeper-server
  namespace: zookeeper
spec:
  keyEncoding: pkcs8
  secretName: zookeeper-server-tls
  commonName: server
  dnsNames:
  - zookeeper-0.zookeeper-headless.zookeeper.svc.cluster.local
  - zookeeper-0
  - zookeeper-1.zookeeper-headless.zookeeper.svc.cluster.local
  - zookeeper-1
  - zookeeper-2.zookeeper-headless.zookeeper.svc.cluster.local
  - zookeeper-2
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
