- name: Update checkers
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Add scheduler to inventory
      add_host:
        name: 'zuul-scheduler-0'
        ansible_kubectl_namespace: zuul
        ansible_connection: kubectl
    - name: Load checker data
      include_vars:
        file: "../checkers.yaml"
    - name: Update Checkers
      delegate_to: 'zuul-scheduler-0'
      update_checkers:
        checkers: "{{ checkers }}"
